import { Launch, Route, Ghat, Booking, Management, Policy } from './types';

export const mockLaunches: Launch[] = [
  {
    _id: '1',
    name: 'M. V. Pubali-12',
    routeIds: ['1', '2'],
    capacity: 600,
    facilities: ['AC', 'Coffee House', 'Intercom', 'Tv', 'VIP Room'],
    contactNumber: '01752-822996',
    alternateContact: '01977-116926',
    status: 'active',
    imageUrl: '/pubali12.png',
    description: 'Comfortable journey with premium facilities. Well-maintained launch for your convenience.',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '2',
    name: 'M. V. Pubali-9',
    routeIds: ['1', '3'],
    capacity: 350,
    facilities: ['Tv', 'Canteen'],
    contactNumber: '01703-559788',
    status: 'active',
    imageUrl: '/pubali9.png',
    description: "It's a long journey where you can enjoy the beauty of nature.",
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    _id: '3',
    name: 'M. V. Pubali-6',
    routeIds: ['2', '3'],
    capacity: 400,
    facilities: ['AC', 'Tv', 'Canteen'],
    contactNumber: '01731-833285',
    status: 'active',
    imageUrl: '/pubali6.png',
    description: 'Premium experience for your journey. Go on a trip to Kuakata Sea Beach on this launch.',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    _id: '4',
    name: 'M. V. Pubali-5',
    routeIds: ['1'],
    capacity: 450,
    facilities: ['AC', 'Tv', 'Canteen', 'VIP Room'],
    contactNumber: '01749-379838',
    alternateContact: '01787-052777',
    status: 'active',
    imageUrl: '/pubali5.png',
    description: 'Comfortable journey with premium facilities. Well-maintained launch for your convenience.',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
];

export const mockRoutes: Route[] = [
  {
    _id: '1',
    name: 'Dhaka to Patuakhali',
    launchIds: ['1'],
    schedules: [
      {
        launchId: '1',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6'], // 6 stops for Pubali-12
      },
    ],
    distance: '271 km',
    estimatedDuration: '10-12 hours',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '2',
    name: 'Patuakhali to Dhaka',
    launchIds: ['1'],
    schedules: [
      {
        launchId: '1',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6'], // 6 stops for Pubali-12
      },
    ],
    distance: '271 km',
    estimatedDuration: '10-12 hours',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '3',
    name: 'Dhaka to Chormontaj',
    launchIds: ['2'],
    schedules: [
      {
        launchId: '2',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6', '7', '8'], // 8 stops for Pubali-9
      },
    ],
    distance: '315 km',
    estimatedDuration: '12-14 hours',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    _id: '4',
    name: 'Chormontaj to Dhaka',
    launchIds: ['2'],
    schedules: [
      {
        launchId: '2',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6', '7', '8'], // 8 stops for Pubali-9
      },
    ],
    distance: '315 km',
    estimatedDuration: '12-14 hours',
    createdAt: '2024-01-16',
    updatedAt: '2024-01-16',
  },
  {
    _id: '5',
    name: 'Dhaka to Khepupara',
    launchIds: ['3'],
    schedules: [
      {
        launchId: '3',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6', '7'], // 7 stops for Pubali-6
      },
    ],
    distance: '290 km',
    estimatedDuration: '12-14 hours',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    _id: '6',
    name: 'Khepupara to Dhaka',
    launchIds: ['3'],
    schedules: [
      {
        launchId: '3',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2', '3', '4', '5', '6', '7'], // 7 stops for Pubali-6
      },
    ],
    distance: '290 km',
    estimatedDuration: '12-14 hours',
    createdAt: '2024-01-17',
    updatedAt: '2024-01-17',
  },
  {
    _id: '7',
    name: 'Dhaka to Elisha',
    launchIds: ['4'],
    schedules: [
      {
        launchId: '4',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2'], // 2 stops for Pubali-5
      },
    ],
    distance: '180 km',
    estimatedDuration: '5-6 hours',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    _id: '8',
    name: 'Elisha to Dhaka',
    launchIds: ['4'],
    schedules: [
      {
        launchId: '4',
        departureTime: '',
        arrivalTime: '',
        daysOfWeek: [],
        ghatIds: ['1', '2'], // 2 stops for Pubali-5
      },
    ],
    distance: '180 km',
    estimatedDuration: '5-6 hours',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
];

export const mockGhats: Ghat[] = [
  {
    _id: '1',
    name: 'Sadarghat Terminal',
    location: 'Dhaka',
    address: 'Sadarghat, Old Dhaka',
    coordinates: { lat: 23.7104, lng: 90.4074 },
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter', 'Restaurant'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '2',
    name: 'Chandpur Ghat',
    location: 'Chandpur',
    address: 'Chandpur Launch Terminal',
    coordinates: { lat: 23.2228, lng: 90.6506 },
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '5',
    name: 'Elisha Ghat',
    location: 'Bhola',
    address: 'Elisha Launch Terminal',
    facilities: ['Parking', 'Ticket Counter'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '6',
    name: 'Patuakhali Terminal',
    location: 'Patuakhali',
    address: 'Patuakhali Launch Terminal',
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '7',
    name: 'Wise Ghat Terminal',
    location: 'Dhaka',
    address: 'Wise Ghat, Dhaka',
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter', 'Restaurant'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '8',
    name: 'Chormontaj Ghat',
    location: 'Bhola',
    address: 'Chormontaj Launch Terminal',
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '9',
    name: 'Khepupara Ghat',
    location: 'Patuakhali',
    address: 'Khepupara Launch Terminal',
    facilities: ['Parking', 'Waiting Area', 'Ticket Counter'],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];

export const mockBookings: Booking[] = [
  {
    _id: '1',
    title: 'Online Booking',
    description: 'Book your tickets online through our website or contact us directly.',
    contactInfo: {
      phone: '01752-822996',
      email: 'booking@padmanavigation.com',
      address: 'Sadarghat Terminal, Dhaka',
    },
    instructions: [
      'Contact us at least 24 hours before your journey',
      'Provide your full name and contact information',
      'Confirm your booking before the journey date',
    ],
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];

export const mockManagement: Management[] = [
  {
    _id: '1',
    name: 'Ali Asgor',
    position: 'Chief Executive Officer',
    description: 'Visionary leader with extensive experience in maritime operations and strategic growth.',
    order: 1,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '2',
    name: 'Babul Ahmed',
    position: 'Operations Director',
    description: 'Ensuring seamless daily operations and efficient fleet management.',
    order: 2,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '3',
    name: 'Md Khalek',
    position: 'Operations Director',
    description: 'Driving operational excellence and optimizing service delivery.',
    order: 3,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '4',
    name: 'Md Akbar',
    position: 'Managing Director',
    description: 'Overseeing key business functions and fostering strategic partnerships.',
    order: 4,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '5',
    name: 'Md Nadim',
    position: 'Managing Director',
    description: 'Responsible for business development and market expansion.',
    order: 5,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '6',
    name: 'K M Nazrul Islam',
    position: 'Managing Director',
    description: 'Guiding the company\'s long-term vision and growth initiatives.',
    order: 6,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '7',
    name: 'Md Hossain',
    position: 'Safety & Compliance Director',
    description: 'Upholding the highest safety standards and regulatory compliance.',
    order: 7,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '8',
    name: 'Hafeez Islam',
    position: 'Customer Relations Manager',
    description: 'Dedicated to ensuring exceptional customer satisfaction and loyalty.',
    order: 8,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];

export const mockPolicies: Policy[] = [
  {
    _id: '1',
    title: 'Safety Guidelines',
    content: 'Passengers must follow all safety instructions provided by the crew. Life jackets are available for all passengers. Smoking is strictly prohibited on board.',
    category: 'Safety',
    order: 1,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '2',
    title: 'Refund Policy',
    content: 'Refunds are available if cancellation is made at least 24 hours before departure. Cancellation fees may apply. Please contact our booking office for refund requests.',
    category: 'Refund',
    order: 2,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    _id: '3',
    title: 'Terms of Service',
    content: 'By booking a journey with Padma Navigation Co., passengers agree to abide by all terms and conditions. The company reserves the right to refuse service to anyone who violates these terms.',
    category: 'Terms',
    order: 3,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
];
